language: python
python:
  - "2.7"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

install:
  - curl https://static.rust-lang.org/rustup.sh | linux32 sh -s -- --prefix=/usr/local --disable-sudo
  - pip install wheel
  - make develop
