[package]
name = "libsourcemap"
version = "0.2.1"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "libsourcemap"
crate-type = ["cdylib", "rlib"]

[dependencies]
sourcemap = "0.6.2"
error-chain = "0.5.0"
