[package]
name = "libsourcemap"
version = "0.3.2"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "libsourcemap"
crate-type = ["cdylib", "rlib"]

[dependencies]
sourcemap = "0.7.0"
error-chain = "0.5.0"
memmap = "0.4.0"
